[project]
name = "python-hexagonal"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "jose-matos-9281", email = "58991817+jose-matos-9281@users.noreply.github.com" }
]
requires-python = ">=3.12"
dependencies = []

[build-system]
requires = ["uv_build>=0.9.16,<0.10.0"]
build-backend = "uv_build"
