"""create tables contactos

Revision ID: 9af7e2346422
Revises: 
Create Date: 2026-03-18 15:35:41.802808

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9af7e2346422'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('afiliado',
    sa.Column('cd_afiliado', sa.String(length=36), nullable=False),
    sa.Column('nss', sa.String(), nullable=True),
    sa.Column('cedula', sa.String(), nullable=True),
    sa.Column('edad', sa.Integer(), nullable=True),
    sa.Column('sexo', sa.String(), nullable=True),
    sa.Column('parentesco', sa.String(), nullable=True),
    sa.Column('nombre', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('cd_afiliado', name='pk_afiliado')
    )
    op.create_table('aggregates_contacto',
    sa.Column('originator_id', sa.String(length=36), nullable=False),
    sa.Column('aggregate_name', sa.String(length=255), nullable=False),
    sa.Column('originator_version', sa.Integer(), nullable=False),
    sa.Column('topic', sa.Text(), nullable=False),
    sa.Column('state', sa.LargeBinary(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('originator_id', 'aggregate_name', name=op.f('pk_aggregates_contacto'))
    )
    op.create_table('aggregates_contacto_events',
    sa.Column('originator_id', sa.String(length=36), nullable=False),
    sa.Column('aggregate_name', sa.String(length=255), nullable=False),
    sa.Column('originator_version', sa.Integer(), nullable=False),
    sa.Column('topic', sa.Text(), nullable=False),
    sa.Column('state', sa.LargeBinary(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('originator_id', 'aggregate_name', 'originator_version', name=op.f('pk_aggregates_contacto_events'))
    )
    op.create_table('aggregates_entidad_contacto',
    sa.Column('originator_id', sa.String(length=36), nullable=False),
    sa.Column('aggregate_name', sa.String(length=255), nullable=False),
    sa.Column('originator_version', sa.Integer(), nullable=False),
    sa.Column('topic', sa.Text(), nullable=False),
    sa.Column('state', sa.LargeBinary(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('originator_id', 'aggregate_name', name=op.f('pk_aggregates_entidad_contacto'))
    )
    op.create_table('aggregates_entidad_contacto_events',
    sa.Column('originator_id', sa.String(length=36), nullable=False),
    sa.Column('aggregate_name', sa.String(length=255), nullable=False),
    sa.Column('originator_version', sa.Integer(), nullable=False),
    sa.Column('topic', sa.Text(), nullable=False),
    sa.Column('state', sa.LargeBinary(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('originator_id', 'aggregate_name', 'originator_version', name=op.f('pk_aggregates_entidad_contacto_events'))
    )
    op.create_table('estado_validacion_contacto',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id', name='pk_estado_validacion_contacto'),
    sa.UniqueConstraint('nombre', name='uq_estado_validacion_contacto_nombre')
    )
    op.create_table('inbox',
    sa.Column('message_id', sa.String(length=36), nullable=False),
    sa.Column('handler', sa.String(length=255), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('failed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('message_id', 'handler', name=op.f('pk_inbox'))
    )
    op.create_index('idx_inbox_processed', 'inbox', ['processed_at'], unique=False)
    op.create_table('outbox',
    sa.Column('message_id', sa.String(length=36), nullable=False),
    sa.Column('topic', sa.String(length=255), nullable=False),
    sa.Column('message', sa.LargeBinary(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('message_id', name=op.f('pk_outbox'))
    )
    op.create_index('idx_outbox_published', 'outbox', ['published_at'], unique=False)
    op.create_index('idx_outbox_topic', 'outbox', ['topic'], unique=False)
    op.create_table('tipo_contacto',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id', name='pk_tipo_contacto'),
    sa.UniqueConstraint('nombre', name='uq_tipo_contacto_nombre')
    )
    op.create_table('tipo_entidad',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id', name='pk_tipo_entidad'),
    sa.UniqueConstraint('nombre', name='uq_tipo_entidad_nombre')
    )
    op.create_table('validacion_contacto_entidad',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id', name='pk_validacion_contacto_entidad'),
    sa.UniqueConstraint('nombre', name='uq_validacion_contacto_entidad_nombre')
    )
    op.create_table('contacto',
    sa.Column('id_contacto', sa.Uuid(), nullable=False),
    sa.Column('id_tipo_contacto', sa.Integer(), nullable=False),
    sa.Column('contacto', sa.String(length=255), nullable=False),
    sa.Column('estado', sa.Integer(), nullable=False),
    sa.Column('usuario_creacion', sa.Uuid(), nullable=True),
    sa.Column('usuario_validacion', sa.Uuid(), nullable=True),
    sa.Column('fecha_validacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['estado'], ['estado_validacion_contacto.id'], name='fk_contacto_estado'),
    sa.ForeignKeyConstraint(['id_tipo_contacto'], ['tipo_contacto.id'], name='fk_contacto_tipo_contacto'),
    sa.PrimaryKeyConstraint('id_contacto', name='pk_contacto'),
    sa.UniqueConstraint('id_tipo_contacto', 'contacto', name='uq_contacto_tipo_contacto')
    )
    op.create_table('entidad',
    sa.Column('id_entidad', sa.Uuid(), nullable=False),
    sa.Column('id_tipo_entidad', sa.Integer(), nullable=False),
    sa.Column('valor', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['id_tipo_entidad'], ['tipo_entidad.id'], name='fk_entidad_tipo_entidad'),
    sa.PrimaryKeyConstraint('id_entidad', name='pk_entidad'),
    sa.UniqueConstraint('id_tipo_entidad', 'valor', name='uq_entidad_tipo_valor')
    )
    op.create_table('entidad_contacto',
    sa.Column('id_entidad', sa.Uuid(), nullable=False),
    sa.Column('id_contacto', sa.Uuid(), nullable=False),
    sa.Column('validacion', sa.Integer(), nullable=False),
    sa.Column('usuario_creacion', sa.Uuid(), nullable=True),
    sa.Column('usuario_validacion', sa.Uuid(), nullable=True),
    sa.Column('fecha_validacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_contacto'], ['contacto.id_contacto'], name='fk_entidad_contacto_contacto'),
    sa.ForeignKeyConstraint(['id_entidad'], ['entidad.id_entidad'], name='fk_entidad_contacto_entidad'),
    sa.ForeignKeyConstraint(['validacion'], ['validacion_contacto_entidad.id'], name='fk_entidad_contacto_validacion'),
    sa.PrimaryKeyConstraint('id_entidad', 'id_contacto', name='pk_entidad_contacto')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('entidad_contacto')
    op.drop_table('entidad')
    op.drop_table('contacto')
    op.drop_table('validacion_contacto_entidad')
    op.drop_table('tipo_entidad')
    op.drop_table('tipo_contacto')
    op.drop_index('idx_outbox_topic', table_name='outbox')
    op.drop_index('idx_outbox_published', table_name='outbox')
    op.drop_table('outbox')
    op.drop_index('idx_inbox_processed', table_name='inbox')
    op.drop_table('inbox')
    op.drop_table('estado_validacion_contacto')
    op.drop_table('aggregates_entidad_contacto_events')
    op.drop_table('aggregates_entidad_contacto')
    op.drop_table('aggregates_contacto_events')
    op.drop_table('aggregates_contacto')
    op.drop_table('afiliado')
    # ### end Alembic commands ###
